Cleanup and add support for m2bf2, bib2lod.
sul-dlss/bibframe-work-validation pull request #31
Opened 2017-04-18 19:54 UTC by jgreben

Use Rspec's --require flag to call a given converter (see spec/helpers). Make sample tests pass for various converters.

2017-04-18 20:18 UTC, ndushay requested changes
on a fairly cursory glance, this looks fine except for the helper file name I noted.  (get rid of xquery term altogether? I dunno).

I'll be happy to merge when you've addressed that

2017-04-18 20:18 UTC, ndushay commented on spec/support/m2bf2_xquery_helpers.rb
> +# helper methods for rspec
I'm wondering if the name of this file is misleading because it currently has xquery in it.  xquery is bf1 converter, xslt for bf2 converter ...

2017-04-18 22:17 UTC, jgreben commented on spec/support/m2bf2_xquery_helpers.rb
> +# helper methods for rspec
Ok, I renamed the files. I also changed the `rspec --require` file names to just (e.g.) m2bf2.rb, so a command line to run the tests against m2bf2 would now be `rspec spec/titles/responsibilityStatement_from_245_246_spec.rb --tag bf2 -r m2bf2.rb`.

I am going to submit a separate PR to update the README with all this info..

2017-04-18 22:18 UTC, jgreben commented on spec/support/m2bf2_xquery_helpers.rb
> +# helper methods for rspec
By the way, if you know of a better way to run all the desired tests using a specific converter (without having to duplicate a lot of calls in all of the spec files) let me know.

2017-04-18 22:41 UTC, ndushay commented on spec/spec_helper.rb
> +require 'support/m2bf2_xquery_helpers'
is this right?  do these files still exist?  Or am I reviewing this too soon?

2017-04-18 22:44 UTC, jgreben commented on spec/spec_helper.rb
> +require 'support/m2bf2_xquery_helpers'
oops...fixed.

2017-04-18 23:01 UTC, ndushay requested changes
dang it - I think this really is the last requested change ...

2017-04-18 23:01 UTC, ndushay commented on spec/m2bf2.rb
> +RSpec.configure { |c| c.before(:each) { MARC2BF_GRAPH_METHOD ||= 'marc_to_graph_m2bf2_xquery' } }
well, crap, here's that pesky xquery again.  Sorry I didn't catch all this in one pass.

2017-04-18 23:49 UTC, jgreben commented
@ndushay Ok, I think it is all buttoned up now...I hope!

2017-04-19 00:36 UTC, ndushay commented
I'm merging this, but you should grep the code to find xquery -- it's still showing up in the README and some other spots in this PR.  But let's just move on this.  Maybe make a separate issue to deal with the remaining xquery references.

2017-04-19 00:36 UTC, ndushay approved these changes

2017-04-19 00:37 UTC, merged

2017-04-19 00:52 UTC, jgreben commented
I started a new branch to update the readme and the comments that include `xquery`